id: python-mcp-development
name: Python MCP Server Development
description: Complete toolkit for building Model Context Protocol (MCP) servers in Python using the official SDK with FastMCP. Includes instructions for best practices, a prompt for generating servers, and an expert chat mode for guidance.
tags:
  - python
  - mcp
  - model-context-protocol
  - fastmcp
  - server-development
items:
  - path: instructions/python-mcp-server.instructions.md
    kind: instruction
  - path: prompts/python-mcp-server-generator.prompt.md
    kind: prompt
  - path: agents/python-mcp-expert.agent.md
    kind: agent
display: {}
